"""add server metrics

Revision ID: 067343cd3ec4
Revises: f4fc2c9f11e2
Create Date: 2026-07-30 18:58:43.683722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '067343cd3ec4'
down_revision: Union[str, None] = 'f4fc2c9f11e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('server_metric_history',
    sa.Column('server_id', sa.UUID(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('cpu_percent', sa.Float(), nullable=True),
    sa.Column('ram_percent', sa.Float(), nullable=True),
    sa.Column('disk_percent_used', sa.Float(), nullable=True),
    sa.Column('net_bytes_sent', sa.BigInteger(), nullable=True),
    sa.Column('net_bytes_recv', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], name=op.f('fk_server_metric_history_server_id_servers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_server_metric_history'))
    )
    op.create_index(op.f('ix_server_metric_history_recorded_at'), 'server_metric_history', ['recorded_at'], unique=False)
    op.create_index(op.f('ix_server_metric_history_server_id'), 'server_metric_history', ['server_id'], unique=False)
    op.add_column('agents', sa.Column('cpu_percent', sa.Float(), nullable=True))
    op.add_column('agents', sa.Column('ram_total_mb', sa.Integer(), nullable=True))
    op.add_column('agents', sa.Column('ram_used_mb', sa.Integer(), nullable=True))
    op.add_column('agents', sa.Column('ram_percent', sa.Float(), nullable=True))
    op.add_column('agents', sa.Column('disks', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('agents', sa.Column('net_bytes_sent', sa.BigInteger(), nullable=True))
    op.add_column('agents', sa.Column('net_bytes_recv', sa.BigInteger(), nullable=True))
    op.add_column('agents', sa.Column('uptime_seconds', sa.BigInteger(), nullable=True))
    op.add_column('agents', sa.Column('metrics_updated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agents', 'metrics_updated_at')
    op.drop_column('agents', 'uptime_seconds')
    op.drop_column('agents', 'net_bytes_recv')
    op.drop_column('agents', 'net_bytes_sent')
    op.drop_column('agents', 'disks')
    op.drop_column('agents', 'ram_percent')
    op.drop_column('agents', 'ram_used_mb')
    op.drop_column('agents', 'ram_total_mb')
    op.drop_column('agents', 'cpu_percent')
    op.drop_index(op.f('ix_server_metric_history_server_id'), table_name='server_metric_history')
    op.drop_index(op.f('ix_server_metric_history_recorded_at'), table_name='server_metric_history')
    op.drop_table('server_metric_history')
    # ### end Alembic commands ###
