"""add server network path history

Revision ID: 06b167a6611a
Revises: 8f8737344773
Create Date: 2026-08-10 11:40:26.157423

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '06b167a6611a'
down_revision: Union[str, None] = '8f8737344773'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('server_network_path_history',
    sa.Column('server_id', sa.UUID(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('target', sa.String(length=255), nullable=False),
    sa.Column('reachable', sa.Boolean(), nullable=False),
    sa.Column('hops', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], name=op.f('fk_server_network_path_history_server_id_servers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_server_network_path_history'))
    )
    op.create_index(op.f('ix_server_network_path_history_recorded_at'), 'server_network_path_history', ['recorded_at'], unique=False)
    op.create_index(op.f('ix_server_network_path_history_server_id'), 'server_network_path_history', ['server_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_server_network_path_history_server_id'), table_name='server_network_path_history')
    op.drop_index(op.f('ix_server_network_path_history_recorded_at'), table_name='server_network_path_history')
    op.drop_table('server_network_path_history')
    # ### end Alembic commands ###
