"""configurable alert rules

Revision ID: 0967fdb34f50
Revises: 067343cd3ec4
Create Date: 2026-07-31 10:08:15.794150

"""
import uuid
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0967fdb34f50'
down_revision: Union[str, None] = '067343cd3ec4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

PERMISSION_CODE = "alerts.manage"
PERMISSION_DESCRIPTION = "Configurar reglas de alertas de servidores (umbrales, mensajes, cooldown)"

# Reproduce today's hardcoded metric_thresholds.py behavior as real, editable rows so
# removing the Python constants doesn't silently change what fires. scope_id=NULL => applies
# to every server. metric_target=NULL for disk rules => evaluate the single worst disk.
DEFAULT_RULES = [
    ("RAM alta (global)", "ram_percent", None, "gte", 90.0, "warning",
     "Uso de RAM en '{hostname}' alcanzó {value:.1f}% (umbral {threshold:.0f}%)."),
    ("RAM crítica (global)", "ram_percent", None, "gte", 96.0, "critical",
     "Uso de RAM en '{hostname}' alcanzó {value:.1f}% (umbral {threshold:.0f}%)."),
    ("Disco con poco espacio (global)", "disk_percent_used", None, "gte", 85.0, "warning",
     "El disco {mount} de '{hostname}' alcanzó {value:.1f}% de uso (umbral {threshold:.0f}%)."),
    ("Disco crítico (global)", "disk_percent_used", None, "gte", 95.0, "critical",
     "El disco {mount} de '{hostname}' alcanzó {value:.1f}% de uso (umbral {threshold:.0f}%)."),
]


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alert_events', sa.Column('server_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_alert_events_server_id'), 'alert_events', ['server_id'], unique=False)
    op.create_foreign_key(op.f('fk_alert_events_server_id_servers'), 'alert_events', 'servers', ['server_id'], ['id'], ondelete='CASCADE')
    op.add_column('alert_rules', sa.Column('metric_target', sa.String(length=255), nullable=True))
    op.add_column('alert_rules', sa.Column('custom_message', sa.Text(), nullable=True))
    op.add_column('alert_rules', sa.Column('cooldown_minutes', sa.Integer(), nullable=False, server_default='30'))
    op.alter_column('alert_rules', 'scope_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###

    bind = op.get_bind()

    for name, metric, metric_target, condition, threshold, severity, message in DEFAULT_RULES:
        bind.execute(
            sa.text(
                """
                INSERT INTO alert_rules
                    (id, name, scope_type, scope_id, metric, metric_target, condition,
                     threshold, severity, custom_message, cooldown_minutes, enabled)
                VALUES
                    (:id, :name, 'server', NULL, :metric, :metric_target, :condition,
                     :threshold, :severity, :message, 30, true)
                """
            ),
            {
                "id": uuid.uuid4(),
                "name": name,
                "metric": metric,
                "metric_target": metric_target,
                "condition": condition,
                "threshold": threshold,
                "severity": severity,
                "message": message,
            },
        )

    permission_id = uuid.uuid4()
    bind.execute(
        sa.text("INSERT INTO permissions (id, code, description) VALUES (:id, :code, :description)"),
        {"id": permission_id, "code": PERMISSION_CODE, "description": PERMISSION_DESCRIPTION},
    )
    admin_role_id = bind.execute(
        sa.text("SELECT id FROM roles WHERE name = 'Administrador' AND is_system_role = true LIMIT 1")
    ).scalar()
    if admin_role_id is not None:
        bind.execute(
            sa.text("INSERT INTO role_permissions (role_id, permission_id) VALUES (:role_id, :permission_id)"),
            {"role_id": admin_role_id, "permission_id": permission_id},
        )


def downgrade() -> None:
    bind = op.get_bind()

    permission_id = bind.execute(
        sa.text("SELECT id FROM permissions WHERE code = :code"), {"code": PERMISSION_CODE}
    ).scalar()
    if permission_id is not None:
        bind.execute(sa.text("DELETE FROM role_permissions WHERE permission_id = :id"), {"id": permission_id})
        bind.execute(sa.text("DELETE FROM permissions WHERE id = :id"), {"id": permission_id})

    bind.execute(
        sa.text("DELETE FROM alert_rules WHERE name = ANY(:names)"),
        {"names": [r[0] for r in DEFAULT_RULES]},
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('alert_rules', 'scope_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('alert_rules', 'cooldown_minutes')
    op.drop_column('alert_rules', 'custom_message')
    op.drop_column('alert_rules', 'metric_target')
    op.drop_constraint(op.f('fk_alert_events_server_id_servers'), 'alert_events', type_='foreignkey')
    op.drop_index(op.f('ix_alert_events_server_id'), table_name='alert_events')
    op.drop_column('alert_events', 'server_id')
    # ### end Alembic commands ###
