"""deployment support: system repo path/build command, platform secrets

Revision ID: 15c4bc2ef3f7
Revises: 4df26c5a0242
Create Date: 2026-07-30 08:05:42.179581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '15c4bc2ef3f7'
down_revision: Union[str, None] = '4df26c5a0242'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('platform_secrets',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value_encrypted', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_platform_secrets'))
    )
    op.create_index(op.f('ix_platform_secrets_key'), 'platform_secrets', ['key'], unique=True)
    op.add_column('systems', sa.Column('repo_local_path', sa.String(length=500), nullable=True))
    op.add_column('systems', sa.Column('deploy_build_command', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('systems', 'deploy_build_command')
    op.drop_column('systems', 'repo_local_path')
    op.drop_index(op.f('ix_platform_secrets_key'), table_name='platform_secrets')
    op.drop_table('platform_secrets')
    # ### end Alembic commands ###
