"""add user site and phone, seed rbac data

Revision ID: 17164779b525
Revises: 648f6cbfcf1f
Create Date: 2026-07-30 14:19:18.887803

"""
import uuid
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import UUID


revision: str = '17164779b525'
down_revision: Union[str, None] = '648f6cbfcf1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


PERMISSIONS = [
    ("systems.manage", "Crear, editar y eliminar sistemas"),
    ("servers.manage", "Crear, editar y eliminar servidores"),
    ("services.manage", "Iniciar, detener, reiniciar y administrar servicios"),
    ("backups.manage", "Crear jobs de respaldo y ejecutar backup/restore"),
    ("config.manage", "Editar configuración y secretos de servicios"),
    ("versions.manage", "Crear versiones y ejecutar rollbacks de versión"),
    ("deployments.manage", "Ejecutar despliegues y rollbacks de despliegue"),
    ("documents.manage", "Subir y eliminar documentos"),
    ("inventory.manage", "Administrar licencias y dependencias"),
    ("notifications.manage", "Administrar canales de notificación y envíos de prueba"),
    ("platform_secrets.manage", "Administrar secretos globales de la plataforma"),
    ("users.manage", "Crear, editar y eliminar usuarios"),
    ("roles.manage", "Crear, editar y eliminar perfiles (roles) y permisos"),
    ("sites.manage", "Crear, editar y eliminar sedes"),
]

ROLES = [
    ("Administrador", "Acceso total a la plataforma CITI", True, [code for code, _ in PERMISSIONS]),
    (
        "Operador",
        "Gestiona sistemas, servidores, servicios, backups, versiones, despliegues, documentos, inventario y notificaciones",
        False,
        [
            "systems.manage",
            "servers.manage",
            "services.manage",
            "backups.manage",
            "versions.manage",
            "deployments.manage",
            "documents.manage",
            "inventory.manage",
            "notifications.manage",
        ],
    ),
    ("Solo lectura", "Solo puede visualizar información, sin permisos de administración", False, []),
]


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('site_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_users_site_id'), 'users', ['site_id'], unique=False)
    op.create_foreign_key(op.f('fk_users_site_id_sites'), 'users', 'sites', ['site_id'], ['id'])
    # ### end Alembic commands ###

    permissions_table = sa.table(
        "permissions", sa.column("id", UUID(as_uuid=True)), sa.column("code", sa.String), sa.column("description", sa.Text)
    )
    roles_table = sa.table(
        "roles",
        sa.column("id", UUID(as_uuid=True)),
        sa.column("name", sa.String),
        sa.column("description", sa.Text),
        sa.column("is_system_role", sa.Boolean),
    )
    role_permissions_table = sa.table(
        "role_permissions", sa.column("role_id", UUID(as_uuid=True)), sa.column("permission_id", UUID(as_uuid=True))
    )

    permission_ids: dict[str, uuid.UUID] = {code: uuid.uuid4() for code, _ in PERMISSIONS}
    op.bulk_insert(
        permissions_table,
        [{"id": permission_ids[code], "code": code, "description": description} for code, description in PERMISSIONS],
    )

    for name, description, is_system_role, codes in ROLES:
        role_id = uuid.uuid4()
        op.bulk_insert(
            roles_table,
            [{"id": role_id, "name": name, "description": description, "is_system_role": is_system_role}],
        )
        if codes:
            op.bulk_insert(
                role_permissions_table,
                [{"role_id": role_id, "permission_id": permission_ids[code]} for code in codes],
            )


def downgrade() -> None:
    op.execute("DELETE FROM role_permissions")
    op.execute("DELETE FROM user_role_assignments")
    op.execute("DELETE FROM roles")
    op.execute("DELETE FROM permissions")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_users_site_id_sites'), 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_site_id'), table_name='users')
    op.drop_column('users', 'site_id')
    op.drop_column('users', 'phone')
    # ### end Alembic commands ###
