"""add server usage tags

Revision ID: 1bfde95c506e
Revises: 701fdae4c982
Create Date: 2026-08-04 08:52:18.980789

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '1bfde95c506e'
down_revision: Union[str, None] = '701fdae4c982'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('servers', sa.Column('usage_tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('servers', 'usage_tags')
    # ### end Alembic commands ###
