"""add maintenance windows

Revision ID: 20d091b58c72
Revises: 8180f5707745
Create Date: 2026-09-01 13:07:11.589282

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '20d091b58c72'
down_revision: Union[str, None] = '8180f5707745'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('maintenance_windows',
    sa.Column('scope_type', sa.Enum('server', 'site', name='maintenance_scope'), nullable=False),
    sa.Column('scope_id', sa.UUID(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_maintenance_windows_created_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_maintenance_windows'))
    )
    op.create_index(op.f('ix_maintenance_windows_scope_id'), 'maintenance_windows', ['scope_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_maintenance_windows_scope_id'), table_name='maintenance_windows')
    op.drop_table('maintenance_windows')
    # ### end Alembic commands ###
