"""user sites many to many

Revision ID: 24c383c027bc
Revises: 7067661b4750
Create Date: 2026-07-31 12:27:43.296642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '24c383c027bc'
down_revision: Union[str, None] = '7067661b4750'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_sites',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('site_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], name=op.f('fk_user_sites_site_id_sites'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_sites_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'site_id', name=op.f('pk_user_sites'))
    )

    # Preserve every existing 1:1 user->site assignment as a row in the new join table
    # before the old scalar column is dropped.
    op.execute("INSERT INTO user_sites (user_id, site_id) SELECT id, site_id FROM users WHERE site_id IS NOT NULL")

    op.drop_index('ix_users_site_id', table_name='users')
    op.drop_constraint('fk_users_site_id_sites', 'users', type_='foreignkey')
    op.drop_column('users', 'site_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('site_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('fk_users_site_id_sites', 'users', 'sites', ['site_id'], ['id'])
    op.create_index('ix_users_site_id', 'users', ['site_id'], unique=False)

    # Lossy: a user with multiple sites collapses back to an arbitrary single one.
    op.execute(
        """
        UPDATE users u
        SET site_id = (SELECT us.site_id FROM user_sites us WHERE us.user_id = u.id LIMIT 1)
        """
    )

    op.drop_table('user_sites')
    # ### end Alembic commands ###
