"""add agent disk_health

Revision ID: 39f5a4a774be
Revises: 06b167a6611a
Create Date: 2026-08-12 08:22:38.785075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '39f5a4a774be'
down_revision: Union[str, None] = '06b167a6611a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('disk_health', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agents', 'disk_health')
    # ### end Alembic commands ###
