"""backup job source_path and restore target path

Revision ID: 4df26c5a0242
Revises: 8dabd5f95b6d
Create Date: 2026-07-28 12:47:54.452010

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '4df26c5a0242'
down_revision: Union[str, None] = '8dabd5f95b6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('backup_jobs', sa.Column('source_path', sa.String(length=500), nullable=False))
    op.add_column('restore_operations', sa.Column('restored_to_path', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('restore_operations', 'restored_to_path')
    op.drop_column('backup_jobs', 'source_path')
    # ### end Alembic commands ###
