"""server accountability features

Revision ID: 701fdae4c982
Revises: cb1738c53170
Create Date: 2026-07-31 14:57:06.079919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '701fdae4c982'
down_revision: Union[str, None] = 'cb1738c53170'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('server_events',
    sa.Column('server_id', sa.UUID(), nullable=False),
    sa.Column('log_name', sa.String(length=50), nullable=False),
    sa.Column('event_record_id', sa.BigInteger(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=255), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], name=op.f('fk_server_events_server_id_servers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_server_events')),
    sa.UniqueConstraint('server_id', 'log_name', 'event_record_id', name='uq_server_events_dedup')
    )
    op.create_index(op.f('ix_server_events_occurred_at'), 'server_events', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_server_events_server_id'), 'server_events', ['server_id'], unique=False)
    op.create_table('server_notes',
    sa.Column('server_id', sa.UUID(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_server_notes_author_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], name=op.f('fk_server_notes_server_id_servers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_server_notes'))
    )
    op.create_index(op.f('ix_server_notes_created_at'), 'server_notes', ['created_at'], unique=False)
    op.create_index(op.f('ix_server_notes_server_id'), 'server_notes', ['server_id'], unique=False)
    op.add_column('agents', sa.Column('net_sent_rate_mbps', sa.Float(), nullable=True))
    op.add_column('agents', sa.Column('net_recv_rate_mbps', sa.Float(), nullable=True))
    op.add_column('agents', sa.Column('disk_read_mbps', sa.Float(), nullable=True))
    op.add_column('agents', sa.Column('disk_write_mbps', sa.Float(), nullable=True))
    op.add_column('agents', sa.Column('top_cpu_processes', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('agents', sa.Column('top_ram_processes', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('agents', sa.Column('processes_updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('alert_events', sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('alert_events', sa.Column('acknowledged_by_id', sa.UUID(), nullable=True))
    op.create_foreign_key(op.f('fk_alert_events_acknowledged_by_id_users'), 'alert_events', 'users', ['acknowledged_by_id'], ['id'], ondelete='SET NULL')
    op.add_column('servers', sa.Column('primary_responsible_user_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_servers_primary_responsible_user_id'), 'servers', ['primary_responsible_user_id'], unique=False)
    op.create_foreign_key(op.f('fk_servers_primary_responsible_user_id_users'), 'servers', 'users', ['primary_responsible_user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_servers_primary_responsible_user_id_users'), 'servers', type_='foreignkey')
    op.drop_index(op.f('ix_servers_primary_responsible_user_id'), table_name='servers')
    op.drop_column('servers', 'primary_responsible_user_id')
    op.drop_constraint(op.f('fk_alert_events_acknowledged_by_id_users'), 'alert_events', type_='foreignkey')
    op.drop_column('alert_events', 'acknowledged_by_id')
    op.drop_column('alert_events', 'acknowledged_at')
    op.drop_column('agents', 'processes_updated_at')
    op.drop_column('agents', 'top_ram_processes')
    op.drop_column('agents', 'top_cpu_processes')
    op.drop_column('agents', 'disk_write_mbps')
    op.drop_column('agents', 'disk_read_mbps')
    op.drop_column('agents', 'net_recv_rate_mbps')
    op.drop_column('agents', 'net_sent_rate_mbps')
    op.drop_index(op.f('ix_server_notes_server_id'), table_name='server_notes')
    op.drop_index(op.f('ix_server_notes_created_at'), table_name='server_notes')
    op.drop_table('server_notes')
    op.drop_index(op.f('ix_server_events_server_id'), table_name='server_events')
    op.drop_index(op.f('ix_server_events_occurred_at'), table_name='server_events')
    op.drop_table('server_events')
    # ### end Alembic commands ###
