"""make user email nullable

Revision ID: 7067661b4750
Revises: 0967fdb34f50
Create Date: 2026-07-31 12:03:53.597850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '7067661b4750'
down_revision: Union[str, None] = '0967fdb34f50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###
