"""add agent disk_io and port_connections

Revision ID: 8180f5707745
Revises: 39f5a4a774be
Create Date: 2026-08-12 09:19:20.957011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '8180f5707745'
down_revision: Union[str, None] = '39f5a4a774be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('disk_io', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('agents', sa.Column('port_connections', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agents', 'port_connections')
    op.drop_column('agents', 'disk_io')
    # ### end Alembic commands ###
