"""add dni to users

Revision ID: 8dabd5f95b6d
Revises: cf280a760a6e
Create Date: 2026-07-26 13:57:39.568035

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '8dabd5f95b6d'
down_revision: Union[str, None] = 'cf280a760a6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('dni', sa.String(length=15), nullable=True))
    op.execute("UPDATE users SET dni = '12345678' WHERE email = 'leomike17@gmail.com'")
    op.alter_column('users', 'dni', nullable=False)
    op.create_index(op.f('ix_users_dni'), 'users', ['dni'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_dni'), table_name='users')
    op.drop_column('users', 'dni')
    # ### end Alembic commands ###
