"""add agent system info fields

Revision ID: 8f8737344773
Revises: 1bfde95c506e
Create Date: 2026-08-05 08:58:02.489122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '8f8737344773'
down_revision: Union[str, None] = '1bfde95c506e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('kernel_version', sa.String(length=100), nullable=True))
    op.add_column('agents', sa.Column('cpu_model', sa.String(length=255), nullable=True))
    op.add_column('agents', sa.Column('load_average_1m', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agents', 'load_average_1m')
    op.drop_column('agents', 'cpu_model')
    op.drop_column('agents', 'kernel_version')
    # ### end Alembic commands ###
