"""initial schema

Revision ID: cf280a760a6e
Revises: 
Create Date: 2026-07-25 20:59:07.659410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'cf280a760a6e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_rules',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('scope_type', sa.Enum('server', 'service', 'system', name='alert_scope'), nullable=False),
    sa.Column('scope_id', sa.UUID(), nullable=False),
    sa.Column('metric', sa.String(length=100), nullable=False),
    sa.Column('condition', sa.Enum('gt', 'lt', 'gte', 'lte', 'eq', name='alert_condition'), nullable=False),
    sa.Column('threshold', sa.Float(), nullable=False),
    sa.Column('severity', sa.Enum('info', 'warning', 'critical', name='alert_severity'), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alert_rules'))
    )
    op.create_index(op.f('ix_alert_rules_scope_id'), 'alert_rules', ['scope_id'], unique=False)
    op.create_table('environments',
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_environments')),
    sa.UniqueConstraint('code', name=op.f('uq_environments_code'))
    )
    op.create_table('notification_channels',
    sa.Column('type', sa.Enum('email', 'telegram', 'whatsapp', 'teams', name='notification_channel_type'), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('config_encrypted', sa.Text(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification_channels'))
    )
    op.create_table('permissions',
    sa.Column('code', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_permissions')),
    sa.UniqueConstraint('code', name=op.f('uq_permissions_code'))
    )
    op.create_table('roles',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_system_role', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles')),
    sa.UniqueConstraint('name', name=op.f('uq_roles_name'))
    )
    op.create_table('sites',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sites')),
    sa.UniqueConstraint('code', name=op.f('uq_sites_code'))
    )
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('mfa_secret', sa.String(length=255), nullable=True),
    sa.Column('mfa_enabled', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('alert_events',
    sa.Column('alert_rule_id', sa.UUID(), nullable=False),
    sa.Column('triggered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('open', 'resolved', name='alert_event_status'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['alert_rule_id'], ['alert_rules.id'], name=op.f('fk_alert_events_alert_rule_id_alert_rules'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alert_events'))
    )
    op.create_index(op.f('ix_alert_events_alert_rule_id'), 'alert_events', ['alert_rule_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=150), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.String(length=100), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_audit_logs_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_id'), 'audit_logs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_type'), 'audit_logs', ['entity_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('network_devices',
    sa.Column('site_id', sa.UUID(), nullable=True),
    sa.Column('type', sa.Enum('switch', 'router', 'firewall', 'nas', 'ups', name='network_device_type'), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('vendor', sa.String(length=100), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('online', 'offline', 'degraded', 'unknown', name='server_status'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], name=op.f('fk_network_devices_site_id_sites')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_network_devices'))
    )
    op.create_index(op.f('ix_network_devices_site_id'), 'network_devices', ['site_id'], unique=False)
    op.create_table('role_permissions',
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('permission_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], name=op.f('fk_role_permissions_permission_id_permissions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_role_permissions_role_id_roles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id', name=op.f('pk_role_permissions'))
    )
    op.create_table('servers',
    sa.Column('site_id', sa.UUID(), nullable=True),
    sa.Column('hostname', sa.String(length=255), nullable=False),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('os_type', sa.Enum('linux', 'windows', name='os_type'), nullable=False),
    sa.Column('os_version', sa.String(length=100), nullable=True),
    sa.Column('cpu_cores', sa.Integer(), nullable=True),
    sa.Column('ram_mb', sa.Integer(), nullable=True),
    sa.Column('disk_gb', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('online', 'offline', 'degraded', 'unknown', name='server_status'), nullable=False),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], name=op.f('fk_servers_site_id_sites')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_servers'))
    )
    op.create_index(op.f('ix_servers_hostname'), 'servers', ['hostname'], unique=False)
    op.create_index(op.f('ix_servers_site_id'), 'servers', ['site_id'], unique=False)
    op.create_table('systems',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('slug', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('criticality', sa.Enum('low', 'medium', 'high', 'critical', name='system_criticality'), nullable=False),
    sa.Column('status', sa.Enum('active', 'maintenance', 'retired', name='system_status'), nullable=False),
    sa.Column('owner_user_id', sa.UUID(), nullable=True),
    sa.Column('repo_url', sa.String(length=500), nullable=True),
    sa.Column('default_branch', sa.String(length=100), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], name=op.f('fk_systems_owner_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_systems'))
    )
    op.create_index(op.f('ix_systems_slug'), 'systems', ['slug'], unique=True)
    op.create_table('agents',
    sa.Column('server_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=True),
    sa.Column('cert_fingerprint', sa.String(length=255), nullable=True),
    sa.Column('enrollment_token_hash', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('pending', 'active', 'revoked', 'unreachable', name='agent_status'), nullable=False),
    sa.Column('last_heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('enrolled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], name=op.f('fk_agents_server_id_servers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agents')),
    sa.UniqueConstraint('server_id', name=op.f('uq_agents_server_id'))
    )
    op.create_table('dependencies',
    sa.Column('system_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Enum('library', 'service', 'external_api', name='dependency_type'), nullable=False),
    sa.Column('version', sa.String(length=100), nullable=True),
    sa.Column('criticality', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['system_id'], ['systems.id'], name=op.f('fk_dependencies_system_id_systems'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dependencies'))
    )
    op.create_index(op.f('ix_dependencies_system_id'), 'dependencies', ['system_id'], unique=False)
    op.create_table('documents',
    sa.Column('system_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('doc_type', sa.Enum('manual_tecnico', 'manual_usuario', 'arquitectura', 'diagrama', 'script', 'pdf', 'imagen', 'video', 'procedimiento', name='document_type'), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=True),
    sa.Column('uploaded_by_id', sa.UUID(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['system_id'], ['systems.id'], name=op.f('fk_documents_system_id_systems'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], name=op.f('fk_documents_uploaded_by_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_documents'))
    )
    op.create_index(op.f('ix_documents_system_id'), 'documents', ['system_id'], unique=False)
    op.create_table('licenses',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('vendor', sa.String(length=255), nullable=True),
    sa.Column('system_id', sa.UUID(), nullable=True),
    sa.Column('server_id', sa.UUID(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('seats', sa.Integer(), nullable=True),
    sa.Column('cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], name=op.f('fk_licenses_server_id_servers')),
    sa.ForeignKeyConstraint(['system_id'], ['systems.id'], name=op.f('fk_licenses_system_id_systems')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_licenses'))
    )
    op.create_index(op.f('ix_licenses_expiry_date'), 'licenses', ['expiry_date'], unique=False)
    op.create_index(op.f('ix_licenses_server_id'), 'licenses', ['server_id'], unique=False)
    op.create_index(op.f('ix_licenses_system_id'), 'licenses', ['system_id'], unique=False)
    op.create_table('notification_logs',
    sa.Column('channel_id', sa.UUID(), nullable=False),
    sa.Column('alert_event_id', sa.UUID(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('sent', 'failed', name='notification_status'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['alert_event_id'], ['alert_events.id'], name=op.f('fk_notification_logs_alert_event_id_alert_events')),
    sa.ForeignKeyConstraint(['channel_id'], ['notification_channels.id'], name=op.f('fk_notification_logs_channel_id_notification_channels'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification_logs'))
    )
    op.create_index(op.f('ix_notification_logs_channel_id'), 'notification_logs', ['channel_id'], unique=False)
    op.create_table('services',
    sa.Column('system_id', sa.UUID(), nullable=False),
    sa.Column('server_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('type', sa.Enum('frontend', 'backend', 'database', 'cache', 'proxy', 'windows_service', 'pm2_process', 'ftp', 'smtp', 'cron_job', 'other', name='service_type'), nullable=False),
    sa.Column('control_strategy', sa.Enum('systemd', 'windows_service', 'pm2', 'docker', 'script', name='control_strategy'), nullable=False),
    sa.Column('control_identifier', sa.String(length=255), nullable=True),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('health_check_url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('running', 'stopped', 'degraded', 'unknown', name='service_status'), nullable=False),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], name=op.f('fk_services_server_id_servers')),
    sa.ForeignKeyConstraint(['system_id'], ['systems.id'], name=op.f('fk_services_system_id_systems'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_services')),
    sa.UniqueConstraint('system_id', 'name', name='uq_service_system_name')
    )
    op.create_index(op.f('ix_services_server_id'), 'services', ['server_id'], unique=False)
    op.create_index(op.f('ix_services_system_id'), 'services', ['system_id'], unique=False)
    op.create_table('system_versions',
    sa.Column('system_id', sa.UUID(), nullable=False),
    sa.Column('version_number', sa.String(length=50), nullable=False),
    sa.Column('git_commit_hash', sa.String(length=40), nullable=True),
    sa.Column('git_branch', sa.String(length=100), nullable=True),
    sa.Column('release_notes', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('active', 'rolled_back', 'deprecated', name='version_status'), nullable=False),
    sa.Column('released_by_id', sa.UUID(), nullable=True),
    sa.Column('released_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['released_by_id'], ['users.id'], name=op.f('fk_system_versions_released_by_id_users')),
    sa.ForeignKeyConstraint(['system_id'], ['systems.id'], name=op.f('fk_system_versions_system_id_systems'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_system_versions'))
    )
    op.create_index(op.f('ix_system_versions_system_id'), 'system_versions', ['system_id'], unique=False)
    op.create_table('user_role_assignments',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('scope_system_id', sa.UUID(), nullable=True),
    sa.Column('granted_by_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['granted_by_id'], ['users.id'], name=op.f('fk_user_role_assignments_granted_by_id_users')),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_user_role_assignments_role_id_roles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scope_system_id'], ['systems.id'], name=op.f('fk_user_role_assignments_scope_system_id_systems'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_role_assignments_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_role_assignments'))
    )
    op.create_index(op.f('ix_user_role_assignments_role_id'), 'user_role_assignments', ['role_id'], unique=False)
    op.create_index(op.f('ix_user_role_assignments_scope_system_id'), 'user_role_assignments', ['scope_system_id'], unique=False)
    op.create_index(op.f('ix_user_role_assignments_user_id'), 'user_role_assignments', ['user_id'], unique=False)
    op.create_table('backup_jobs',
    sa.Column('service_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('database', 'files', 'full', name='backup_type'), nullable=False),
    sa.Column('schedule_cron', sa.String(length=100), nullable=True),
    sa.Column('retention_days', sa.Integer(), nullable=False),
    sa.Column('storage_path', sa.String(length=500), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_backup_jobs_created_by_id_users')),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], name=op.f('fk_backup_jobs_service_id_services'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_backup_jobs'))
    )
    op.create_index(op.f('ix_backup_jobs_service_id'), 'backup_jobs', ['service_id'], unique=False)
    op.create_table('certificates',
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('server_id', sa.UUID(), nullable=True),
    sa.Column('service_id', sa.UUID(), nullable=True),
    sa.Column('issuer', sa.String(length=255), nullable=True),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('auto_renew', sa.Boolean(), nullable=False),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], name=op.f('fk_certificates_server_id_servers')),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], name=op.f('fk_certificates_service_id_services')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_certificates'))
    )
    op.create_index(op.f('ix_certificates_domain'), 'certificates', ['domain'], unique=False)
    op.create_index(op.f('ix_certificates_server_id'), 'certificates', ['server_id'], unique=False)
    op.create_index(op.f('ix_certificates_service_id'), 'certificates', ['service_id'], unique=False)
    op.create_index(op.f('ix_certificates_valid_to'), 'certificates', ['valid_to'], unique=False)
    op.create_table('config_entries',
    sa.Column('service_id', sa.UUID(), nullable=False),
    sa.Column('environment_id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('is_secret', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('updated_by_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['environment_id'], ['environments.id'], name=op.f('fk_config_entries_environment_id_environments')),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], name=op.f('fk_config_entries_service_id_services'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_config_entries_updated_by_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_config_entries')),
    sa.UniqueConstraint('service_id', 'environment_id', 'key', name='uq_config_entry_key')
    )
    op.create_index(op.f('ix_config_entries_environment_id'), 'config_entries', ['environment_id'], unique=False)
    op.create_index(op.f('ix_config_entries_service_id'), 'config_entries', ['service_id'], unique=False)
    op.create_table('cron_jobs',
    sa.Column('service_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('schedule', sa.String(length=100), nullable=False),
    sa.Column('command', sa.Text(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_status', sa.String(length=20), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], name=op.f('fk_cron_jobs_service_id_services'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cron_jobs'))
    )
    op.create_index(op.f('ix_cron_jobs_service_id'), 'cron_jobs', ['service_id'], unique=False)
    op.create_table('deployments',
    sa.Column('system_id', sa.UUID(), nullable=False),
    sa.Column('version_id', sa.UUID(), nullable=True),
    sa.Column('source', sa.Enum('git', 'zip', 'manual', name='deployment_source'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'success', 'failed', 'rolled_back', name='deployment_status'), nullable=False),
    sa.Column('triggered_by_id', sa.UUID(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('log_output', sa.Text(), nullable=True),
    sa.Column('rollback_of_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['rollback_of_id'], ['deployments.id'], name=op.f('fk_deployments_rollback_of_id_deployments')),
    sa.ForeignKeyConstraint(['system_id'], ['systems.id'], name=op.f('fk_deployments_system_id_systems'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['triggered_by_id'], ['users.id'], name=op.f('fk_deployments_triggered_by_id_users')),
    sa.ForeignKeyConstraint(['version_id'], ['system_versions.id'], name=op.f('fk_deployments_version_id_system_versions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_deployments'))
    )
    op.create_index(op.f('ix_deployments_system_id'), 'deployments', ['system_id'], unique=False)
    op.create_table('service_action_logs',
    sa.Column('service_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.Enum('start', 'stop', 'restart', 'force_restart', name='service_action'), nullable=False),
    sa.Column('triggered_by_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'success', 'failed', name='action_result_status'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('output', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], name=op.f('fk_service_action_logs_service_id_services'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['triggered_by_id'], ['users.id'], name=op.f('fk_service_action_logs_triggered_by_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_service_action_logs'))
    )
    op.create_index(op.f('ix_service_action_logs_service_id'), 'service_action_logs', ['service_id'], unique=False)
    op.create_table('service_dependencies',
    sa.Column('service_id', sa.UUID(), nullable=False),
    sa.Column('depends_on_service_id', sa.UUID(), nullable=False),
    sa.Column('dependency_type', sa.String(length=100), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['depends_on_service_id'], ['services.id'], name=op.f('fk_service_dependencies_depends_on_service_id_services'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], name=op.f('fk_service_dependencies_service_id_services'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_service_dependencies')),
    sa.UniqueConstraint('service_id', 'depends_on_service_id', name='uq_service_dependency')
    )
    op.create_index(op.f('ix_service_dependencies_depends_on_service_id'), 'service_dependencies', ['depends_on_service_id'], unique=False)
    op.create_index(op.f('ix_service_dependencies_service_id'), 'service_dependencies', ['service_id'], unique=False)
    op.create_table('backup_runs',
    sa.Column('backup_job_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'success', 'failed', name='run_status'), nullable=False),
    sa.Column('triggered_by', sa.Enum('manual', 'scheduled', name='trigger_type'), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('sha256_hash', sa.String(length=64), nullable=True),
    sa.Column('storage_path', sa.String(length=500), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['backup_job_id'], ['backup_jobs.id'], name=op.f('fk_backup_runs_backup_job_id_backup_jobs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_backup_runs'))
    )
    op.create_index(op.f('ix_backup_runs_backup_job_id'), 'backup_runs', ['backup_job_id'], unique=False)
    op.create_table('config_entry_history',
    sa.Column('config_entry_id', sa.UUID(), nullable=False),
    sa.Column('previous_value', sa.Text(), nullable=True),
    sa.Column('changed_by_id', sa.UUID(), nullable=True),
    sa.Column('changed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('change_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['changed_by_id'], ['users.id'], name=op.f('fk_config_entry_history_changed_by_id_users')),
    sa.ForeignKeyConstraint(['config_entry_id'], ['config_entries.id'], name=op.f('fk_config_entry_history_config_entry_id_config_entries'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_config_entry_history'))
    )
    op.create_index(op.f('ix_config_entry_history_config_entry_id'), 'config_entry_history', ['config_entry_id'], unique=False)
    op.create_table('restore_operations',
    sa.Column('backup_run_id', sa.UUID(), nullable=False),
    sa.Column('requested_by_id', sa.UUID(), nullable=True),
    sa.Column('target_service_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'running', 'success', 'failed', name='run_status'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['backup_run_id'], ['backup_runs.id'], name=op.f('fk_restore_operations_backup_run_id_backup_runs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requested_by_id'], ['users.id'], name=op.f('fk_restore_operations_requested_by_id_users')),
    sa.ForeignKeyConstraint(['target_service_id'], ['services.id'], name=op.f('fk_restore_operations_target_service_id_services')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_restore_operations'))
    )
    op.create_index(op.f('ix_restore_operations_backup_run_id'), 'restore_operations', ['backup_run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_restore_operations_backup_run_id'), table_name='restore_operations')
    op.drop_table('restore_operations')
    op.drop_index(op.f('ix_config_entry_history_config_entry_id'), table_name='config_entry_history')
    op.drop_table('config_entry_history')
    op.drop_index(op.f('ix_backup_runs_backup_job_id'), table_name='backup_runs')
    op.drop_table('backup_runs')
    op.drop_index(op.f('ix_service_dependencies_service_id'), table_name='service_dependencies')
    op.drop_index(op.f('ix_service_dependencies_depends_on_service_id'), table_name='service_dependencies')
    op.drop_table('service_dependencies')
    op.drop_index(op.f('ix_service_action_logs_service_id'), table_name='service_action_logs')
    op.drop_table('service_action_logs')
    op.drop_index(op.f('ix_deployments_system_id'), table_name='deployments')
    op.drop_table('deployments')
    op.drop_index(op.f('ix_cron_jobs_service_id'), table_name='cron_jobs')
    op.drop_table('cron_jobs')
    op.drop_index(op.f('ix_config_entries_service_id'), table_name='config_entries')
    op.drop_index(op.f('ix_config_entries_environment_id'), table_name='config_entries')
    op.drop_table('config_entries')
    op.drop_index(op.f('ix_certificates_valid_to'), table_name='certificates')
    op.drop_index(op.f('ix_certificates_service_id'), table_name='certificates')
    op.drop_index(op.f('ix_certificates_server_id'), table_name='certificates')
    op.drop_index(op.f('ix_certificates_domain'), table_name='certificates')
    op.drop_table('certificates')
    op.drop_index(op.f('ix_backup_jobs_service_id'), table_name='backup_jobs')
    op.drop_table('backup_jobs')
    op.drop_index(op.f('ix_user_role_assignments_user_id'), table_name='user_role_assignments')
    op.drop_index(op.f('ix_user_role_assignments_scope_system_id'), table_name='user_role_assignments')
    op.drop_index(op.f('ix_user_role_assignments_role_id'), table_name='user_role_assignments')
    op.drop_table('user_role_assignments')
    op.drop_index(op.f('ix_system_versions_system_id'), table_name='system_versions')
    op.drop_table('system_versions')
    op.drop_index(op.f('ix_services_system_id'), table_name='services')
    op.drop_index(op.f('ix_services_server_id'), table_name='services')
    op.drop_table('services')
    op.drop_index(op.f('ix_notification_logs_channel_id'), table_name='notification_logs')
    op.drop_table('notification_logs')
    op.drop_index(op.f('ix_licenses_system_id'), table_name='licenses')
    op.drop_index(op.f('ix_licenses_server_id'), table_name='licenses')
    op.drop_index(op.f('ix_licenses_expiry_date'), table_name='licenses')
    op.drop_table('licenses')
    op.drop_index(op.f('ix_documents_system_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_dependencies_system_id'), table_name='dependencies')
    op.drop_table('dependencies')
    op.drop_table('agents')
    op.drop_index(op.f('ix_systems_slug'), table_name='systems')
    op.drop_table('systems')
    op.drop_index(op.f('ix_servers_site_id'), table_name='servers')
    op.drop_index(op.f('ix_servers_hostname'), table_name='servers')
    op.drop_table('servers')
    op.drop_table('role_permissions')
    op.drop_index(op.f('ix_network_devices_site_id'), table_name='network_devices')
    op.drop_table('network_devices')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_alert_events_alert_rule_id'), table_name='alert_events')
    op.drop_table('alert_events')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('sites')
    op.drop_table('roles')
    op.drop_table('permissions')
    op.drop_table('notification_channels')
    op.drop_table('environments')
    op.drop_index(op.f('ix_alert_rules_scope_id'), table_name='alert_rules')
    op.drop_table('alert_rules')
    # ### end Alembic commands ###
