"""add backup_run purged_at

Revision ID: df29f63231d0
Revises: e9f8cb0bc82e
Create Date: 2026-07-30 17:27:06.423261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'df29f63231d0'
down_revision: Union[str, None] = 'e9f8cb0bc82e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('backup_runs', sa.Column('purged_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('backup_runs', 'purged_at')
    # ### end Alembic commands ###
