"""add synthetic checks

Revision ID: f0697632de15
Revises: 20d091b58c72
Create Date: 2026-09-01 14:23:42.951900

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'f0697632de15'
down_revision: Union[str, None] = '20d091b58c72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('synthetic_check_results',
    sa.Column('service_id', sa.UUID(), nullable=False),
    sa.Column('prober_server_id', sa.UUID(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['prober_server_id'], ['servers.id'], name=op.f('fk_synthetic_check_results_prober_server_id_servers'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], name=op.f('fk_synthetic_check_results_service_id_services'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_synthetic_check_results'))
    )
    op.create_index(op.f('ix_synthetic_check_results_checked_at'), 'synthetic_check_results', ['checked_at'], unique=False)
    op.create_index(op.f('ix_synthetic_check_results_prober_server_id'), 'synthetic_check_results', ['prober_server_id'], unique=False)
    op.create_index(op.f('ix_synthetic_check_results_service_id'), 'synthetic_check_results', ['service_id'], unique=False)
    op.add_column(
        'servers',
        sa.Column('is_synthetic_probe', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('servers', 'is_synthetic_probe')
    op.drop_index(op.f('ix_synthetic_check_results_service_id'), table_name='synthetic_check_results')
    op.drop_index(op.f('ix_synthetic_check_results_prober_server_id'), table_name='synthetic_check_results')
    op.drop_index(op.f('ix_synthetic_check_results_checked_at'), table_name='synthetic_check_results')
    op.drop_table('synthetic_check_results')
    # ### end Alembic commands ###
